jobs:

  - job: Ubuntu_18_04_build
    pool:
      vmImage: 'Ubuntu 18.04'
    strategy:
      matrix:    
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
      maxParallel: 3

    steps:

    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH

    - bash: conda create --quiet --yes -n pylsewave -c conda-forge python='$(python.version)' cython numpy scipy cymem matplotlib
      displayName: Create Anaconda environment

    - script: |
        source activate pylsewave
        python setup.py build_ext --inplace
      displayName: build